version: '3.8'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable_freqairl
    container_name: freqtrade_strategy
    restart: unless-stopped
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./config:/freqtrade/config
      - ./strategies:/freqtrade/user_data/strategies
    ports:
      - "8080:8080"
    command: >
      trade --logfile /freqtrade/user_data/logs/freqtrade.log --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite --config /freqtrade/config/config.json --strategy FreqAIHybridStrategy
